# Generated by Django 5.0.3 on 2024-04-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('b', 'B'), ('m', 'M'), ('ph', 'PH')], default='b', max_length=20),
        ),
        migrations.AlterModelTable(
            name='address',
            table='Address',
        ),
    ]
